services:
  game-server:
    build: .
    ports:
      - "27016:27016"
    volumes:
      - ./src:/usr/src/app/src  # ✅ Mount only the `src` folder
      - ./include:/usr/src/app/include  # ✅ Mount only the `include` folder
    environment:
      - ENV=development
    security_opt:
      - seccomp=unconfined
    networks:
      - mmo_network

networks:
  mmo_network:
    external: true
