services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27016:27016"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    restart: unless-stopped
    networks:
      - mmo_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M
        reservations:
          cpus: "1"
          memory: 1024M

networks:
  mmo_network:
    external: true
