services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "27016:27016"
    environment:
      - LOG_LEVEL=info
      - LOG_LEVEL_NETWORK=warn
      - LOG_LEVEL_GAMELOOP=warn
      - LOG_LEVEL_EVENTS=warn
    restart: unless-stopped
    networks:
      - mmo_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M
        reservations:
          cpus: "1"
          memory: 1024M

networks:
  mmo_network:
    external: true
